### ISSUE TITLE
Group column has ending comma when its the only group field

### ISSUE THREAD

**Issue by johnnymajor** [jdrew1303/sqlgenerate#2]
Nice work on sqlgenerate! Been experimenting with it and I can't seem to track down why this is happening. I am getting a trailing comma after the group by field of "JOHNNY".

The original sql statement sent to sqlite-parser:

```sql
SELECT STATE, LSTNAM, INIT, CUSNUM, BALDUE, ' '  
  FROM QCUSTCDT1                               
UNION 
SELECT STATE, ' ', ' ', 0, SUM(BALDUE), '*'
  FROM QCUSTCDT2                               
 GROUP BY JOHNNY                                   
UNION 
SELECT 'ZZ', ' ', ' ', 0, SUM(BALDUE), '**'
FROM QCUSTCDT3                               
ORDER BY 1,6
```

The statement regenerated from sqlgenerate:

```sql
SELECT state, lstnam, init, cusnum, baldue, ''
 FROM qcustcdt1
UNION
 SELECT state, '', '', 0, SUM(baldue), '*'
 FROM qcustcdt2
 GROUP BY johnny,
UNION
 SELECT 'ZZ', '', '', 0, SUM(baldue), '**'
 FROM qcustcdt3
 ORDER BY 1, 6
```

Attaching the AST that was generated from sqlite-parser
[ast.txt](https://github.com/jdrew1303/sqlgenerate/files/972386/ast.txt)

Thanks for any help/guidance you can supply.

** edited to fix syntax highlighting

**Comment by jdrew1303** [comment]
Hey @johnnymajor 

Thanks :smiley:  I haven't been working on it for a bit. I'm hoping to do a rewrite in the next while. I was waiting for the sqlite parser to support comments so that users could apply transformations to existing sql codebases. 

Ill take a look through it this evening and see what the issue is. If its a small bug Ill patch it. If its something more involved it'll probably be the end of the week before I can get to it :+1: 

I'd also be curious what you're using it for (I've been trying to find use cases for this :thinking: )

I'm also open to pull requests or other issue if there's stuff in there that you think could be improved (the code is a bit :grimacing:)

**Comment by johnnymajor** [comment]
Awesome, thanks for responding.

I currently have something that stores a SQL statement in chunks "results, from, where, order by etc" and at runtime needs to put the statement together to query the db possibly adding additional information like adding/appending the where clause etc. The initial statement chunks currently are created based of a wiziwig a user has to go through. What are the files, columns etc? 

Looking for a way they can enter a valid statement and the application automatically changes the statement based on our requirements and store it in the same chunks we currently do from the wiziwig.  I would be using this "sqlgenerate" to take the modified ast and give me the statement chunk(s) I need.

Hopefully, that made some sense... 

Thanks again.

**Comment by jdrew1303** [comment]
@johnnymajor Cool, that makes sense. I did something similar for Salesforce SOQL project before 👍 We did transformations for performance and governor limits (it forces you to write code with minimum performance levels but people are very bad at it 😁 ).

Ok so Ive limited the issue down to this guy:
https://github.com/jdrew1303/sqlgenerate/blob/master/sqlgenerate.js#L309

I should have time this evening to take a look and I'll patch it and you should be back in business. 👍

**Comment by johnnymajor** [comment]
Awesome!!!

**Comment by jdrew1303** [comment]
Its taken a while but its good to go 👍 This also highlighted an issue with using multiple columns in `ORDER BY`. I'll confess I didn't actually know that you could do that. 🙈😜

[Also on a sidenote Ive published this on NPM so it should be easier to play with. ](https://www.npmjs.com/~jdrew1303)
