### ISSUE TITLE
Parsing offset

### ISSUE THREAD

**Issue by simple-nguyen** [jdrew1303/sqlgenerate#4]
Noticed that the ast does not always contain the offset object when specifying just a LIMIT.

eg. `select 
* 
from 
"test"
limit 5`

will produce an ast of:

```
{
  "type": "statement",
  "variant": "list",
  "statement": [
    {
      "type": "statement",
      "variant": "select",
      "result": [
        {
          "type": "identifier",
          "variant": "star",
          "name": "*"
        }
      ],
      "from": {
        "type": "identifier",
        "variant": "table",
        "name": "test"
      },
      "limit": {
        "type": "expression",
        "variant": "limit",
        "start": {
          "type": "literal",
          "variant": "decimal",
          "value": "5"
        }
      }
    }
  ]
}
```

This will cause the recurser to fail for limit when it tries to do:

`const offset = recurser(n.offset);`

**Comment by jdrew1303** [comment]
Hey @simple-nguyen 
Ill take a look into this over the weekend. :squirrel: 👍

**Comment by jdrew1303** [comment]
Hey @simple-nguyen 
You should be good to go 👍 Ive pushed a new release to NPM with the patch. Any more issues let me know. Id also be curious how you're using the library (its interesting to see what its being used for in the wild 🤔 ☺️ )?

**Comment by simple-nguyen** [comment]
Sweet 👍 

I was using it for a very strange API, which basically was an open API to send SQL queries (ignore the security implications here) and retrieve results. I was using this library to determine certain params and alter the AST and parsing it back to an SQL statement before sending it off.

**Comment by jdrew1303** [comment]
No judgement here 😄 Ive had to do that sort of stuff before. Any other issues or ideas for the library just let me know 👍
